FROM node:22.11 AS build

WORKDIR /app
COPY package.json package-lock.json ./

RUN npm install --omit=optional

COPY . ./

RUN npm run build

FROM nginx:alpine AS production
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

